apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo_mongodb_deployment_1100
  name: argo-mongodb-deployment-1100
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: argo_mongodb_deployment_1100
