apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo_nginx_deployment_5932
  name: argo-nginx-deployment-5932
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argo_nginx_deployment_5932
  strategy: {}
  template:
    metadata:
      labels:
        app: argo_nginx_deployment_5932
    spec:
      containers:
      - image: docker-registry-var.ntnxlab.local/cicd_project_var/nginx:0.1.1
        imagePullPolicy: Always
        name: mongo
        env:
        - name: NODEJS_IP_ADDRESS
          value: '10.42.70.156'
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-cred-var
