apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo_nodejs_deployment_3494
  name: argo-nodejs-deployment-3494
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo_nodejs_deployment_3494
  strategy: {}
  template:
    metadata:
      labels:
        app: argo_nodejs_deployment_3494
    spec:
      containers:
      - image: docker-registry-var.ntnxlab.local/cicd_project_var/nodejs:0.1.1
        imagePullPolicy: Always
        name: nodejs
        env:
        - name: MONGODB_HOST
          value: '10.42.70.152'
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      imagePullSecrets:
        - name: docker-registry-cred-var
